<a href="https://colab.research.google.com/github/dudcoco/machine_deep_learning/blob/main/numpy%EC%84%A4%EB%AA%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.array([1,4,5,8], float)
print(arr) # 출력 결과가 [1., 4,, 5., 8] 인 이유: 실수형이기 때문에 뒤에 소수점이 붙는다

arr = np.array([1,4,5,8]) # 매개변수2에 자료형을 주지 않아도 배열 생성가능
print(arr)
print(type(arr[0])) # 여기선 int 형으로 생성된다

[1. 4. 5. 8.]
[1 4 5 8]
<class 'numpy.int64'>


In [3]:
print(type(arr[3]))
# 넘파이 배열 요소의 타입을 알아낼 땐 type(배열명[인덱스])
print(type(arr))
# 넘파이 배열 타입 확인할 땐 type(배열명)

<class 'numpy.int64'>
<class 'numpy.ndarray'>


### 넘파이 배열, 파이썬 리스트 차이점
- 넘파이 배열 : 동일 데이터 타입만 사용가능, 액세스 빠름
- 파이썬 리스트 : 데이터 타입이 달라도 사용가능, 액세스 느림

In [4]:
# 배열 생성하기
arr = np.array([1,4,5,"8"], float) # 배열을 실수형으로 선언
print(arr) # 출력 결과 모두 실수형임

[1. 4. 5. 8.]


In [5]:
print(type(arr[3])) # 배열 인덱스3 요소에는 "8"이라는 문자형 데이터 값을 주었지만 실수형으로 자동 형변환 되었음

<class 'numpy.float64'>


In [6]:
print(arr.dtype)

# dtype : 배열 전체의 데이터 타입을 반환해줌
# 사용법 : 배열명.dtype

float64


In [7]:
print(arr.shape)

# shape : 배열의 구조를 반환해줌
# 사용법 : 배열명.shape

(4,)


In [8]:
""" 배열의 구조 """

mat = np.array([1,2,5,8], int)
print(mat.shape) # 1행 4열으로 이루어진 배열. 튜플 형태로 구조 출력됨 (열, )

mat = np.array([[1,2,5,8], [1,2,3,4]], int)
print(mat.shape) # 2행 4열으로 이루어진 배열. 튜플 형태로 구조 출력됨 (행, 열)

mat = np.array([
    [[1,2],[4,5],[7,8]],
    [[1,2],[4,5],[7,8]],
    [[1,2],[4,5],[7,8]]], int)
print(mat.shape) # 3차원 3행 2열으로 이루어진 배열. 튜플 형태로 구조 출력됨 (차원, 행, 열)
print(mat)


(4,)
(2, 4)
(3, 3, 2)
[[[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]]


In [9]:
""" dtype """
# 매개변수 dtype으로 넘파이 배열의 데이터 타입 저장. 변수가 사용하는 메모리 크기가 정해짐

arr1 = np.array([[1,2,3.5], [4,5,6.5]], dtype=int) # 결과 : 데이터 타입(dtype)을 int(정수형)으로 지정했기 때문에 3.5나 6.5같은 실수형도 정수형으로 형 변환이 되어서 저장됨
print(arr1)

arr2 = np.array([[1,2,3.5], [4,5,6.5]], dtype=float) # 결과 : 데이터 타입을 실수형으로 지정했기 때문에 정수형도 실수형으로 형변환 되어서 저장됨
print(arr2)

[[1 2 3]
 [4 5 6]]
[[1.  2.  3.5]
 [4.  5.  6.5]]


In [10]:
import sys
arr = np.array([[1,2,3.5], [4,5,6.5]], dtype=np.float64).itemsize
print(arr)

# itemsize : 넘파이 배열에서 각 요소가 차지하는 바이트 확인
# np.float64로 dtype을 선언하면 64비트, 즉 1요소당 8바이트를 차지
# np.float32로 dtype을 선언하면 32비트, 즉 1요소당 4바이트를 차지

arr = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.float64).itemsize
print(arr)

8
8


### 배열의 구조 다루기
- reshape 함수 : 배열의 구조를 변경하고 랭크를 조절. __반드시 전체 요소 개수는 통일__
- 사용법
++ 배열명.reshape(차원, 행, 열)
++ 배열명.reshape(행, 열)
++ 배열명.reshape(-1,) : 전체 요소 개수만큼의 행을 가진 배열을 만듦
++ 배열명.reshape(행, -1) : 행 개수 지정하고 그에 맞게 열 개수도 자동으로 지정하게 함


* -1 사용: 나머지 차원의 크기를 지정했을 때 전체 요소의 개수를 고려하여 마지막 차원이 자동 지정됨

In [11]:
x = np.array([[1,2,3,4], [1,2,3,4]])
print(x)
print(x.shape) # 현재는 2*4
print("="*20)

x = x.reshape(-1, ) # 전체 요소 개수만큼의 행을 가진 배열을 만듦
print(x)
print(x.shape)

[[1 2 3 4]
 [1 2 3 4]]
(2, 4)
[1 2 3 4 1 2 3 4]
(8,)


In [12]:
# range : 범위 지정
x = np.array(range(8)) # 0~7 범위의 값을 가진 배열을 생성
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
x.reshape(2,2) # 2*2 배열로 재구성하려고 하지만, 전체 요소 개수가 8개인데에 반해 2*2배열은 요소개수가 4개임. 전체 개수가 맞지 않아 에러발생
print(x)

ValueError: ignored

In [14]:
x = np.array(range(8)).reshape(4,2)
print(x)
print("="*20)

# -1 사용
x = x.reshape(2, -1) # 2행으로 정하고, 2행에 맞춰서 열을 정의
print(x)
print("="*20)

x = x.reshape(2, 2, -1) # 2차원 2행으로 정하고 나머지 열은 이 두 개에 맞춰서 정의. 전체 요소가 8개이므로 2*2*2가 되어야함
print(x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 2 3]
 [4 5 6 7]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


## flatten 함수 : 데이터 그대로 __1차원__으로 변경
- 데이터의 개수는 그대로 존재하고, 배열의 구조만 변함

In [15]:
x = np.array(range(8)).reshape(2,2,2)
print(x)
print("="*20)
print(x.flatten())
print(x.reshape(-1,)) # x.flatten()과 동일한 결과

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]


## 인덱싱과 슬라이싱
### 1. 인덱싱 : 리스트에 있는 값의 상대적인 주소로 값에 접근
- 넘파이 배열의 인덱스 표현에는 ','을 지원함: [행][열] 또는 [행,열] 형태
- 3차원 텐서 이상은 shape에서 출력되는 랭크 순서대로 인덱싱에 접근

In [16]:
x = np.array([[1,2,3], [4,5,6]], int)
print(x)
print(x[0][0]) # 1번째 행 1번째 열 요소
print(x[0,2]) # 1번째 행 3번째 열 요소
print("="*20)

x[0,1] = 100 # 1번째 행 2번째 열 요소를 100으로 설정
print(x)

[[1 2 3]
 [4 5 6]]
1
3
[[  1 100   3]
 [  4   5   6]]


### 2. 슬라이싱 : 인덱스를 사용하여 리스트의 일부를 잘라내어 반환
- 넘파이 배열은 행과 열을 나누어 슬라이싱할 수 있음

In [17]:
x = np.array([[1,2,3,4,5], [6,7,8,9,10]], int) # x는 2행 5열
print(x[:, 2:]) # :는 행 전체, 2:는 인덱스 2부터 시작하는 열 전체
print("="*20)

print(x[1,1:3]) # 인덱스 1인 행, 인덱스 1~2인 열
print(x[0,1:3]) # 인덱스 0인 행, 인덱스 1~2인 열
print(x[1:3]) # 인덱스 1~2인 행. 근데 이 행렬은 2행짜리이므로 행 인덱스가 1까지밖에 없음. 그래서 이를 넘어가는 인덱스는 그냥 무시함 (에러 발생하지 않음)

[[ 3  4  5]
 [ 8  9 10]]
[7 8]
[2 3]
[[ 6  7  8  9 10]]


In [18]:
# 증가값(step) : 리스트에서 데이터의 요소를 호출할 때 데이터를 건너뛰면서 반환
# [시작 인덱스:마지막 인덱스:증가값]
# 각 랭크에 있는 요소별로 모두 적용 가능

x = np.array(range(15), int).reshape(3, -1) # 3행 5열인 배열
print(x)
print("="*20)

print(x[:,::2]) # 행 전체에서 증가값 2씩
print("="*20)

print(x[::2,::3]) # 열 전체에서 증가값 2씩, 행 전체에서 증가값 3씩

""" 증가값은 [열, 행] 형태임!!!!!!!! 주의해라... """

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]]
[[ 0  3]
 [10 13]]


' 증가값은 [열, 행] 형태임!!!!!!!! 주의해라... '

## 배열 생성 함수
### 1. arange() : range()와 같이 차례대로 값을 생성. (시작인덱스, 마지막인덱스, 증가값)
- range()와 다르게 증가값에 실수형이 입력되어도 값 생성 가능
- 소수점 값을 주기적으로 생성할 떄 유용

In [19]:
print(np.arange(10)) # 0~9
print(np.arange(-5,5)) # -5~4
print(np.arange(0,5,0.5)) # 0~5 범위인데(5 포함 안됨) 증가값이 0.5씩

[0 1 2 3 4 5 6 7 8 9]
[-5 -4 -3 -2 -1  0  1  2  3  4]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


### 2. ones. zeros, empty
1) ones() : 1로만 구성된 넘파이 배열을 생성. 사전에 shape 값을 넣어서 원하는 크기의 넘파이 배열 생성
<br>
2) zeros() : 0으로만 구성된 넘파이 배열을 생성. 사전에 shape 값을 넣어서 원하는 크기의 넘파이 배열 생성
<br>
3) empty() : 활용 가능한 메모리공간 확보하여 반환.

<br>

ones(), zeros() : 먼저 shape의 크기만큼 메모리를 할당하고 그곳에 값을 채움. 해당 메모리 공간에 값이 남았을 경우에는 그 값을 함께 반환
<br>
emtpy() : 메모리 초기화를 하지 않아서 생성될 때마다 다른 값을 반환

- 생성 시점에서 dtype 지정해주면 해당 데이터타입으로 배열 생성


In [20]:
x = np.ones(shape=(5,2), dtype=np.int8) # 5행 2열 크기, 요소가 1로만 이루어진 배열 생성. 데이터 타입은 int8
print(x)
print("="*20)

y = np.zeros(shape=(2,2), dtype=np.float32) # 2행 2열 크기. 요소가 0으로만 이루어진 배열 생성. 데이터 타입은 float32
print(y)
print("="*20)

np.empty(shape=(2,4), dtype=np.float32) # 실수형으로 배열 생성됨. 좀 이상한데...? 찾아보기


[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
[[0. 0.]
 [0. 0.]]


array([[1.4e-45, 0.0e+00, 5.6e-45, 0.0e+00],
       [7.0e-45, 0.0e+00, 1.1e-44, 0.0e+00]], dtype=float32)

### 3. ones_like(배열명), zeros_like(배열명), empty_like(배열명) - (잘 안쓰임)
1) ones_like : 기존 넘파이 배열과 같은 크기로 만들어 내용을 1로 채움
<br>
2) zeros_like : 기존 넘파이 배열과 같은 크기로 만들어 내용을 0으로 채움
<br>
3) empty_like : 기존 넘파이 배열과 같은 크기로 만들어 빈 상태로 *만듦*

In [21]:
x = np.arange(12).reshape(3,4) # 0~11 까지 값으로 3행 4열의 배열 생성
print(x)
print("="*20)

print(np.ones_like(x))
print("="*20)
print(np.zeros_like(x))
print("="*20)
print(np.empty_like(x))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### 4. identity(n, dtype), eye(행개수 N, 열개수 M, 시작인덱스 k), diag(행렬명)
1) identity : n*n 단위행렬 생성
<br>
2) eye : 시작점과 행렬 크기를 지정, 단위행렬 생성. 자주 쓰이진 않음
<br>
3) diag : 행렬의 대각성분 값을 추출

In [22]:
# identity
print(np.identity(n=3, dtype=int))
print("="*20)
print(np.identity(n=4, dtype=int))
print("="*20)

# eye
print(np.eye(N=3, M=5)) # 3행 5열
print("="*20)
print(np.eye(N=3, M=5, k=2)) # k는 열의 값을 기준으로 시작 인덱스. 인덱스 2인 열부터 단위행렬 만들기
print("="*20)

# diag
mat = np.arange(9).reshape(3,3)
print(mat)
print("="*20)
print(np.diag(mat))
print("="*20)
print(np.diag(mat, k=1)) # k는 열의 값을 기준으로 시작 인덱스. 인덱스 1인 열부터 대각성분 값 추출

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]
[1 5]


## 통계 분석 함수
1) uniform 함수 : 균등분포 함수
- np.random.uniform(시작값, 끝값, 데이터개수)

2) normal 함수 : 정규분포 함수
- np.random.normal(평균값, 분산, 데이터개수)

In [23]:
# uniform
print(np.random.uniform(0,5,10)) # 범위 0~5, 10개
print("="*20)

# normal
print(np.random.normal(0,2,10)) # 평균 0, 분산 2, 데이터 10개

[2.24229092 1.89308348 3.19568124 0.99092282 2.77999226 0.40703499
 0.10623164 0.8240065  3.72347434 2.17045001]
[-1.38926323  0.62222263  0.99735957 -1.87507119 -1.15958337  0.40379932
  2.11934422 -1.9734347   0.06798457 -1.8454191 ]


# 넘파이 배열 연산
## 연산 함수 : 배열 내부 연산을 지원하는 함수
- 축(axis) : 배열의 랭크가 증가할 때마다 새로운 축이 추가되어 차원이 증가
- sum 함수 : 각 요소의 합을 반환

In [24]:
import numpy as np
arr = np.arange(1, 11) # 1부터 10의 요소를 가지는 배열
print(arr)
print(arr.sum()) #

[ 1  2  3  4  5  6  7  8  9 10]
55


In [25]:
arr = np.arange(1,13).reshape(3,4) # 1~12까지의 값, 3행 4열
print(arr)
print("="*20)

print(arr.sum(axis=0)) # axis=0 : 열을 축으로
print("="*20)
print(arr.sum(axis=1)) # axis=1 : 행을 축으로

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[15 18 21 24]
[10 26 42]


In [27]:
arr = np.arange(1,13).reshape(3,4)
third = np.array([arr,arr,arr])
print(third)
print("="*20)
print(third.sum(axis=0)) # 차원을 축으로해서 합
print("="*20)
print(third.sum(axis=1)) # 열을 축으로해서 합
print("="*20)
print(third.sum(axis=2)) # 행을 축으로해서 합

# axis 주의하자!!!!!!!!!!!

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]]
[[15 18 21 24]
 [15 18 21 24]
 [15 18 21 24]]
[[10 26 42]
 [10 26 42]
 [10 26 42]]


In [33]:
arr = np.arange(1,13).reshape(3,4) # 3행 4열
print(arr)
print("="*20)

print(arr.mean(axis=1)) # axis=1 축(여기선 행)을 기준으로 평균 계산
print("="*20)

print(arr.std()) # 전체 값에 대한 표준편차 계산
print("="*20)

print(arr.std(axis=0)) # axis=0 축(여기선 열)을 기준으로 표준편차 계산
print("="*20)

print(np.sqrt(arr)) # 각 요소에 제곱근 연산. 여기선 axis 못 씀!!!!!!!!!!

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 2.5  6.5 10.5]
3.452052529534663
[3.26598632 3.26598632 3.26598632 3.26598632]
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]]


## 연결 함수 : 두 객체 간의 결합을 지원하는 함수
- vstack 함수 : vertical. 배열을 수직으로(가로) 붙여 하나의 행렬 생성
np.vstack((행렬1, 행렬2))
- hstack 함수 : horizontal. 배열을 수평으로(세로) 붙여 하나의 행렬 생성
np.hstack((행렬1, 행렬2))

In [49]:
# 넘파이는 열 벡터를 표현할 수 없음 (행=0, 열=1인 행렬을 못 만듦) -> 2차원 행렬 형태로 표현해야함
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print(np.vstack((v1, v2))) # np.vstack(()) 괄호 두개
print(np.hstack((v1, v2))) # np.hstack(()) 괄호 두개
print("="*20)

# v1 = np.arange(1,10).reshape(3,3)
# v2 = np.arange(10,19).reshape(3,3)
# print(np.vstack((v1,v2)))
# print(np.hstack((v1,v2)))
# print("="*20)

v1 = v1.reshape(-1,1)
v2 = v2.reshape(-1,1)
print(v1)
print(v2)
print("="*20)
print(np.hstack((v1, v2))) # 2차원 행렬 형태로 표현한 열 벡터를 hstack으로 연결
print("="*20)

v1 = np.array([[2,3], [4,5], [6,7]])
v2 = np.array([[8,9], [1,2], [3,4]])
print(np.vstack((v1, v2)))


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1]
 [2]
 [3]]
[[4]
 [5]
 [6]]
[[1 4]
 [2 5]
 [3 6]]
[[2 3]
 [4 5]
 [6 7]
 [8 9]
 [1 2]
 [3 4]]


- concatenate 함수 : 축을 고려하여 두 개의 배열을 결합. np.concatenate((행렬1, 행렬2)), axis=n)
<br>
스택 계열의 함수와 달리 생성될 배열과 소스가 되는 배열의 __차원__이 같아야 함
<br>
두 벡터를 결합하고 싶다면, 해당 벡터를 일단 2차원 배열 꼴로 변환 후 행렬로 나타내야 함

In [54]:
# v1과 v2 모두 사실상 행렬이지만 벡터의 형태임
v1 = np.array([[1,2,3]])
v2 = np.array([[4,5,6]])

print(np.concatenate((v1,v2), axis=0)) # vstack과 동일. axis=0으로 행(가로)을 기준으로 연결

[[1 2 3]
 [4 5 6]]


- .T : 대각선을 기준으로 바꾸는 것. Aij -> Aji 로 바꿈

In [56]:
v1 = np.array([1,2,3,4]).reshape(2,2)
v2 = np.array([[5,6]]).T # .T : 행렬을 대각선을 기준으로 바꾸는 것
print(v1)
print("="*20)
print(v2)
print("="*20)

print(np.concatenate((v1,v2), axis=1)) # hstack과 동일. axis=1로 열(세로)을 기준으로 연결

[[1 2]
 [3 4]]
[[5]
 [6]]
[[1 2 5]
 [3 4 6]]


## 사칙연산 함수
### - 넘파이는 파이썬과 동일하게 배열 간 사칙연산 지원 -> 행렬과 행렬, 벡터와 벡터 간 사칙연산 가능
### - 같은 배열의 구조일 때 요소별로 연산 -> 두 배열의 구조가 동일하다면 같은 인덱스 요소들끼리 연산

In [59]:
x = np.arange(1,7).reshape(2,3)
print(x)
print("="*20)
print(x+x) # 덧셈
print("="*20)
print(x-x) # 뺄셈
print("="*20)
print(x/x) # 나눗셈, 몫
print("="*20)
print(x**x) # 제곱

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[    1     4    27]
 [  256  3125 46656]]


### 배열 간의 곱셈에서는 요소별 연산, 벡터의 내적 연산 가능
- 벡터의 내적 : 두 배열 간의 곱셈
- M\*L과 L\*N 내적하면 M*N 크기의 배열이 결과로 출력됨

### dot 함수 : 벡터의 내적 연산


In [61]:
x = np.arange(1,7).reshape(2,3)
y = np.arange(1,7).reshape(3,2)
print(x)
print("="*20)
print(y)
print("="*20)

print(x.dot(y)) # x와 y의 내적 표현print("="*20)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[22 28]
 [49 64]]


### 브로드캐스팅 연산 : 하나의 행렬과 스칼라 값들 간의 연산이나 행렬과 벡터 간의 연산


In [64]:
x = np.arange(1,10).reshape(3,3)
print(x)
print("="*20)

print(x+10)
print("="*20)

print(x-2)
print("="*20)

print(x//3)
print("="*20)

print(x**2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[0 0 1]
 [1 1 2]
 [2 2 3]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [66]:
x = np.arange(1,13).reshape(4,3)
print(x)
print("="*20)

v = np.arange(10,40,10) # 10부터 40까지 증가값 10 -> [10,20,30]
print(v)
print("="*20)

print(x+v) # v는 1행 3열이고, x는 4행 3열임. x의 행 개수인 4에 맞춰 v가 4*3 행렬로 복제됨

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[10 20 30]
[[11 22 33]
 [14 25 36]
 [17 28 39]
 [20 31 42]]


# 넘파이 텐서 연산의 특징
1. (장점)C와 유사한 형태로 메모리를 관리하면서, C와 같은 연산 속도로 계산 가능
2. 연결 연산처럼 여러 배열을 붙이는 연산은 리스트에 비해 느림


## 비교 연산
-> 연산 결과는 항상 불린형을 가진 배열로 추출
### 브로드캐스팅 비교 연산
-> 하나의 스칼라 값과 벡터 간의 비교 연산은 벡터 내 전체요소에 적용


In [68]:
import numpy as np
x = np.array([4,3,2,6,8,5])
print(x>3) # 요소값들이 3보다 크면 True 작으면 False

[ True False False  True  True  True]


### 요소별 비교 연산
-> 두개의 배열 간 배열의 구조가 동일한 경우, 같은 위치에 있는 요소들끼리 비교 연산
-> [1 > 2,3 > 1,0 > 7]과 같이 연산이 실시된 후 이를 반환

In [69]:
x = np.array([1,3,0])
y = np.array([2,1,7])
print(x>y) # x>y인 요소값은 True, 작으면 False

[False  True False]


## 비교 연산 함수
### all, any
1. all 함수 : 배열 내부의 모든 값이 참이면 True, 하나라도 참이 아니면 False (AND)
2. any 함수 : 배열 내부의 값 중 하나라도 참이면 True, 모두 거짓일 때만 False (OR)

In [73]:
x = np.array([4,6,7,3,2])
print(x>3)
print("="*20)

print((x>3).all())
print((x>3).any())
print("="*20)

print((x<10).any())
print((x<10).all())
print((x>10).any())

[ True  True  True False False]
False
True
True
True
False


### 인덱스 반환 함수
- where 함수 : 배열이 불린형으로 이루어졌을 때 참인 값들의 인덱스를 반환
True, False 대신에 참, 거짓인 경우 반환할 값을 지정할 수 있음

In [74]:
x = np.array([4,6,7,3,2])
print(x>5)

print(np.where(x>5)) # x의 요소값이 5보다 큰 것들의 인덱스를 반환함. 배열형태

[False  True  True False False]
(array([1, 2]),)


In [75]:
x = np.array([4,6,7,3,2])
print(np.where(x>5, 10, 20)) # 참일 경우 10 반환, 거짓일 경우 20 반환

[20 10 10 20 20]


### 정렬된 값의 인덱스를 반환해주는 함수
1. argsort(배열명) : 배열 내의 값들을 작은 순서대로 인덱스를 반환
2. argmax(배열명) : 배열 내 값들 중 가장 큰 값의 인덱스를 반환
3. argmin(배열명) : 배열 내 값들 중 가장 작은 값의 인덱스르 반환

-> argmin, argmax 사용 잦음

In [79]:
x = np.array([4,6,7,3,2])
print(np.argsort(x))
print(np.argmax(x))
print(np.argmin(x))

[4 3 0 1 2]
2
4


## 인덱스를 활용한 데이터 추출
### 불린 인덱스 : 배열에 있는 값들을 반환할 특정 조건을 불린형의 배열에 넣어서 추출
-> 인덱스에 들어가는 배열은 불린형이어야함
-> 불린형 배열과 추출 대상이 되는 배열의 구조가 같아야 함

In [81]:
x = np.array([4,6,7,3,2])
print(x>3)
print("="*20)

cond = x>3
print(x[cond]) # 배열 x에서 요소값이 3보다 큰 요소들의 인덱스에 맞는 요소값 반환

print(x.shape)
print(cond.shape)

[ True  True  True False False]
[4 6 7]
(5,)
(5,)


### 팬시 인덱스 : 정수형 배열의 값을 사용하여 해당 정수의 인덱스에 위치한 값을 반환
-> 인덱스 항목에 넣을 배열은 정수로만 구성되어야 함

-> 정수 값의 범위는 대상이 되는 배열이 가지는 인덱스의 범위 내 대상이 되는 배열과 인덱스 구조가 같을 필요는 없음

In [87]:
x = np.array([4,6,7,3,2])
cond = np.array([1,2,0,2,2,2], int) # cond라는 새로운 배열 생성
print(x[cond]) # cond 배열의 요소값을 인덱스로 사용하여 x 배열에서 그 인덱스에 위치한 값을 반환
print("="*20)

print(x.take(cond)) # x[cond]와 동일 표현

x = np.array([[1,4], [9,16]], int)
a = np.array([0,1,1,1,0,0], int)
b = np.array([0,0,0,1,1,1], int)
print(x[a,b])

[6 7 4 7 7 7]
[6 7 4 7 7 7]
[ 1  9  9 16  4  4]
